package com.airgf.app.domain.model

private val avatarDefaultFeatures = AvatarFeatureSet(
    blendShapeOrder = listOf(
        "jawOpen",
        "viseme_sil",
        "viseme_aa",
        "viseme_E",
        "viseme_O",
        "viseme_U",
        "viseme_FF",
        "viseme_PP",
        "viseme_TH",
        "mouthOpen",
        "mouthSmile",
        "mouthFrown",
        "mouthPucker",
        "mouthPress",
        "browInnerUp",
        "browDownLeft",
        "browDownRight",
        "eyeBlinkLeft",
        "eyeBlinkRight",
        "eyeWideLeft",
        "eyeWideRight",
        "eyeSquintLeft",
        "eyeSquintRight",
        "cheekSquintLeft",
        "cheekSquintRight",
    ),
    idleAnimationNames = listOf("Idle", "Breathing", "Talk"),
)

enum class VisualTemplate(
    val displayName: String,
    val modelAssetPath: String,
    val thumbnailAssetPath: String,
    val deliveryMode: AvatarDeliveryMode,
    val expectedSizeBytes: Long,
    val downloadFileName: String = modelAssetPath.substringAfterLast('/'),
    val remoteModelUrl: String? = null,
    val legacyNames: Set<String> = emptySet(),
    val supportsSceneView: Boolean = true,
    val releaseEligible: Boolean = false,
    val supportedPresentations: Set<CompanionPresentation> = emptySet(),
    val preferredVoiceLocaleTags: List<String> = listOf("en-US"),
    val stageVerticalOffset: Float = 0f,
    val proceduralRigAnimation: Boolean = true,
    val fallbackPalette: AvatarFallbackPalette,
    val featureSet: AvatarFeatureSet = avatarDefaultFeatures,
) {
    MAYA(
        displayName = "Maya",
        modelAssetPath = "models/maya.glb",
        thumbnailAssetPath = "models/thumb_maya.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 8_571_204,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.FEMININE),
        fallbackPalette = AvatarFallbackPalette(0xFFE5B08E, 0xFF3B2418, 0xFFFF6F61, 0xFF263238, 0xFF101416),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    NIA(
        displayName = "Nia",
        modelAssetPath = "models/nia.glb",
        thumbnailAssetPath = "models/thumb_nia.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 8_751_964,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.FEMININE),
        fallbackPalette = AvatarFallbackPalette(0xFF8D5D45, 0xFF17120F, 0xFF20B2AA, 0xFF28343A, 0xFF111719),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    SORA(
        displayName = "Sora - Japanese",
        modelAssetPath = "models/sora.glb",
        thumbnailAssetPath = "models/thumb_sora.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 93_615_572,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.FEMININE),
        preferredVoiceLocaleTags = listOf("ja-JP", "en-US"),
        proceduralRigAnimation = true,
        fallbackPalette = AvatarFallbackPalette(0xFFD7A078, 0xFF221A19, 0xFFFFC857, 0xFF30353B, 0xFF141719),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    LEO(
        displayName = "Leo",
        modelAssetPath = "models/leo.glb",
        thumbnailAssetPath = "models/thumb_leo.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 11_210_124,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.MASCULINE),
        fallbackPalette = AvatarFallbackPalette(0xFFD39B76, 0xFF171412, 0xFF4DA3FF, 0xFF27323C, 0xFF10161B),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    MARCUS(
        displayName = "Marcus",
        modelAssetPath = "models/marcus.glb",
        thumbnailAssetPath = "models/thumb_marcus.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 10_008_632,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.MASCULINE),
        fallbackPalette = AvatarFallbackPalette(0xFF86563F, 0xFF14110F, 0xFFFFC857, 0xFF30343A, 0xFF141619),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    KAI(
        displayName = "Kai",
        modelAssetPath = "models/kai.glb",
        thumbnailAssetPath = "models/thumb_kai.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 7_255_732,
        releaseEligible = true,
        supportedPresentations = setOf(CompanionPresentation.MASCULINE),
        fallbackPalette = AvatarFallbackPalette(0xFFD8A47D, 0xFF201B18, 0xFF20B2AA, 0xFF29373A, 0xFF101719),
        featureSet = AvatarFeatureSet(supportsBlink = false, supportsHeadTilt = false),
    ),
    ARIADNA(
        displayName = "Ariadna",
        modelAssetPath = "models/ariadna.glb",
        thumbnailAssetPath = "models/thumb_ariadna.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 6_632_464,
        legacyNames = setOf("ANIME_CUTE", "STYLIZED_SOFT"),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD6C2,
            hairColor = 0xFF2D203B,
            accentColor = 0xFFFF6FB5,
            backdropStartColor = 0xFF2C1639,
            backdropEndColor = 0xFF120814,
        ),
    ),
    GRACY_LEE(
        displayName = "Gracy Lee",
        modelAssetPath = "models/gracy_lee.glb",
        thumbnailAssetPath = "models/thumb_gracy_lee.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 3_291_488,
        legacyNames = setOf("REALISTIC_WARM", "REALISTIC_JAPANESE"),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD9C7,
            hairColor = 0xFF1B1628,
            accentColor = 0xFF86D7FF,
            backdropStartColor = 0xFF1C2745,
            backdropEndColor = 0xFF090E17,
        ),
    ),
    CATWOMAN(
        displayName = "Catwoman",
        modelAssetPath = "models/catwoman.glb",
        thumbnailAssetPath = "models/thumb_catwoman.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 10_783_560,
        legacyNames = setOf("ANIME_COOL", "STYLIZED_PUNK"),
        releaseEligible = false,
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD4BC,
            hairColor = 0xFF0D0D10,
            accentColor = 0xFFFFB347,
            backdropStartColor = 0xFF24111D,
            backdropEndColor = 0xFF070608,
        ),
    ),
    PRIYA(
        displayName = "Priya",
        modelAssetPath = "models/indian_woman_in_saree.glb",
        thumbnailAssetPath = "models/thumb_priya.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 15_361_276,
        legacyNames = setOf("REALISTIC_VIETNAMESE"),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFCB8B63,
            hairColor = 0xFF23120D,
            accentColor = 0xFFFF7A8A,
            backdropStartColor = 0xFF3A1423,
            backdropEndColor = 0xFF0E070A,
        ),
    ),
    ALINA(
        displayName = "Alina",
        modelAssetPath = "models/alina_ip_realistic_asian_woman_animated.glb",
        thumbnailAssetPath = "models/thumb_alina.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 93_615_484,
        legacyNames = setOf("REALISTIC_ELEGANT", "REALISTIC_FILIPINO"),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD7CA,
            hairColor = 0xFF3B220F,
            accentColor = 0xFFD9A8FF,
            backdropStartColor = 0xFF341B47,
            backdropEndColor = 0xFF100714,
        ),
    ),
    NATASHA(
        displayName = "Natasha",
        modelAssetPath = "models/realistic_woman_walking_animated.glb",
        thumbnailAssetPath = "models/thumb_natasha.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 80_230_388,
        legacyNames = emptySet(),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFBD4C1,
            hairColor = 0xFF6A3D2B,
            accentColor = 0xFF9ED5FF,
            backdropStartColor = 0xFF183447,
            backdropEndColor = 0xFF081018,
        ),
    ),
    RUBY(
        displayName = "Ruby",
        modelAssetPath = "models/short-hair-red-head-american.glb",
        thumbnailAssetPath = "models/thumb_ruby.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 100_693_496,
        legacyNames = setOf("REALISTIC_AMERICAN"),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD7C7,
            hairColor = 0xFFB4462F,
            accentColor = 0xFFFF7A5A,
            backdropStartColor = 0xFF422028,
            backdropEndColor = 0xFF14070B,
        ),
    ),
    SOPHIA(
        displayName = "Sophia",
        modelAssetPath = "models/sophia_animated_003_-_animated_3d_woman.glb",
        thumbnailAssetPath = "models/thumb_sophia.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 13_527_864,
        legacyNames = emptySet(),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD3BF,
            hairColor = 0xFF2A1B16,
            accentColor = 0xFFFF9E80,
            backdropStartColor = 0xFF3A2530,
            backdropEndColor = 0xFF12090C,
        ),
    ),
    BEACH_BABE(
        displayName = "Beach Babe",
        modelAssetPath = "models/bouncy_beach_babe_walking_in_bikini_animated.glb",
        thumbnailAssetPath = "models/thumb_beach_babe.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 87_894_744,
        legacyNames = emptySet(),
        releaseEligible = false,
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFC7A7,
            hairColor = 0xFFFFD36A,
            accentColor = 0xFF4DD9D9,
            backdropStartColor = 0xFF0E4F5B,
            backdropEndColor = 0xFF061A23,
        ),
    ),
    NISHA_OFFICE(
        displayName = "Nisha Office",
        modelAssetPath = "models/indian_office_woman.glb",
        thumbnailAssetPath = "models/thumb_nisha_office.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 16_356_492,
        legacyNames = emptySet(),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFD1976F,
            hairColor = 0xFF1B100B,
            accentColor = 0xFF6FA8FF,
            backdropStartColor = 0xFF1C2E46,
            backdropEndColor = 0xFF080E16,
        ),
    ),
    INDIAN_HOODIE(
        displayName = "Indian Hoodie",
        modelAssetPath = "models/indian_teenager__woman_in__hoodie.glb",
        thumbnailAssetPath = "models/thumb_indian_hoodie.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 21_196_744,
        legacyNames = emptySet(),
        releaseEligible = false,
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFD79A72,
            hairColor = 0xFF25120E,
            accentColor = 0xFF9B8CFF,
            backdropStartColor = 0xFF27204B,
            backdropEndColor = 0xFF090812,
        ),
    ),
    HAYLEY_SMITH(
        displayName = "Hayley Smith",
        modelAssetPath = "models/hayley_smith.glb",
        thumbnailAssetPath = "models/thumb_hayley_smith.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 9_305_872,
        legacyNames = emptySet(),
        supportsSceneView = false,
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD2BA,
            hairColor = 0xFFFFC24A,
            accentColor = 0xFFFF6F91,
            backdropStartColor = 0xFF442236,
            backdropEndColor = 0xFF13070F,
        ),
    ),
    RUMBA(
        displayName = "Rumba",
        modelAssetPath = "models/woman_rumba_dancing_-_mulher_dancando_rumba.glb",
        thumbnailAssetPath = "models/thumb_rumba.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 3_329_568,
        legacyNames = emptySet(),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFE6A37D,
            hairColor = 0xFF2A1711,
            accentColor = 0xFFFF4F6D,
            backdropStartColor = 0xFF451827,
            backdropEndColor = 0xFF12070A,
        ),
    ),
    ELENA(
        displayName = "Elena",
        modelAssetPath = "models/realistic_female_character__game-ready_3d_model.glb",
        thumbnailAssetPath = "models/thumb_elena.webp",
        deliveryMode = AvatarDeliveryMode.BUNDLED,
        expectedSizeBytes = 92_745_428,
        legacyNames = emptySet(),
        fallbackPalette = AvatarFallbackPalette(
            skinColor = 0xFFFFD0BD,
            hairColor = 0xFF4B2A1C,
            accentColor = 0xFF6EE7B7,
            backdropStartColor = 0xFF183D35,
            backdropEndColor = 0xFF07120F,
        ),
    ),
    ;

    val isOnDemand: Boolean
        get() = deliveryMode == AvatarDeliveryMode.ON_DEMAND

    fun supports(presentation: CompanionPresentation): Boolean = releaseEligible &&
        (presentation == CompanionPresentation.NEUTRAL || presentation in supportedPresentations)

    companion object {
        private val defaultTemplate = MAYA

        fun fromPersistedName(name: String?): VisualTemplate {
            if (name.isNullOrBlank()) return defaultTemplate

            return entries.firstOrNull { template ->
                template.name == name || template.legacyNames.contains(name)
            } ?: defaultTemplate
        }
    }
}
